name: Push to MAIN_FIAFIT

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (BACKEND_FIAFIT)
    - name: Checkout BACKEND_FIAFIT
      uses: actions/checkout@v2

    # Configurar Git con las credenciales
    - name: Set up Git
      run: |
        git config --global user.name 'gonzalo1998peru'
        git config --global user.email 'gonzalo_huertas_oliva@outlook.es'

    # Clone the MAIN_FIAFIT repository (branch 'BACK')
    - name: Clone MAIN_PROYFIAFIT
      run: |
        git clone --branch BACK https://x-access-token:${{ secrets.access_token_gonzalo }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git MAIN_PROYFIAFIT

    # Copy files from BACKEND_FIAFIT to MAIN_FIAFIT (without unnecessary complexity)
    - name: Copy files
      run: |
        cp -R * ./MAIN_PROYFIAFIT/

    # Commit and push changes to the 'BACK' branch of MAIN_PROYFIAFIT
    - name: Commit and push changes
      run: |
        cd MAIN_PROYFIAFIT
        git add .
        git commit -m "Sync from BACKEND_FIAFIT"
        git push origin BACK
