name: Push to MAIN_FIAFIT

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (BACKEND_FIAFIT)
    - name: Checkout BACKEND_FIAFIT
      uses: actions/checkout@v2

    # Configure Git with credentials
    - name: Set up Git
      run: |
        git config --global user.name 'gonzalo1998peru'
        git config --global user.email 'gonzalo_huertas_oliva@outlook.es'

    # Clone the target repository MAIN_PROYFIAFIT (to branch 'back')
    - name: Clone MAIN_PROYFIAFIT
      env:
        TOKEN_BACK: ${{ secrets.access_token_gonzalo }}  # Secreto configurado con el valor de 'token1'
      run: |
        dir=$(mktemp -d) # Create temporary directory
        git clone --branch back https://x-access-token:${{ secrets.access_token_gonzalo }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git $dir
        echo $dir # Print directory for debugging
        ls -al $dir

    # Copy files from BACKEND_FIAFIT to the cloned MAIN_PROYFIAFIT
    - name: Copy files to MAIN_PROYFIAFIT
      run: |
        cp -r ./* $dir/

    # Commit and push changes to the 'back' branch in MAIN_PROYFIAFIT
    - name: Commit and push changes
      run: |
        cd $dir
        git add .
        git commit -m "Update from BACKEND_FIAFIT"
        git push origin back

    # Clean up the cloned repository
    - name: Clean up
      run: rm -rf $dir
