name: Push to MAIN_FIAFIT

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (BACKEND_FIAFIT)
    - name: Checkout BACKEND_FIAFIT
      uses: actions/checkout@v2

    # Configurar Git con las credenciales
    - name: Set up Git
      run: |
        git config --global user.name 'gonzalo1998peru'
        git config --global user.email 'gonzalo_huertas_oliva@outlook.es'

    # Clone the MAIN_FIAFIT repository (branch 'BACK') into TEMPORAL_CHANGE directory
    - name: Clone MAIN_PROYFIAFIT
      run: |
        git clone --branch BACK https://x-access-token:${{ secrets.access_token_gonzalo }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git TEMPORAL_CHANGE

      # Copy files from BACKEND_FIAFIT to MAIN_PROYFIAFIT
    - name: Copy files from BACKEND_FIAFIT to MAIN_PROYFIAFIT
      run: |
        cd TEMPORAL_CHANGE
        git branch -a
        cd ..

        rsync -av --exclude='.git' --exclude='TEMPORAL_CHANGE' ./ TEMPORAL_CHANGE/
        cd TEMPORAL_CHANGE
        git branch -a
        ls
        echo "1-------------------------------------------------------------------"
        git status
        git add .
        git status
        git commit -m "Sync from BACKEND_FIAFIT"
        git push
        

