name: Push to MAIN_FIAFIT

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (BACKEND_FIAFIT)
    - name: Checkout BACKEND_FIAFIT
      uses: actions/checkout@v2

    # Configure Git with credentials
    - name: Set up Git
      run: |
        git config --global user.name 'gonzalo1998peru'
        git config --global user.email 'gonzalo_huertas_oliva@outlook.es'

    # Clone the target repository MAIN_PROYFIAFIT (to branch 'BACK')
    - name: Clone MAIN_PROYFIAFIT
      env:
        TOKEN_BACK: ${{ secrets.access_token_gonzalo }}  # Secreto configurado con el valor de 'token1'
      run: |
        dir=$(mktemp -d) # Create temporary directory
        git clone --branch BACK https://x-access-token:${{ secrets.access_token_gonzalo }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git $dir
        echo "Cloned into: $dir"
        ls -al $dir

    # Verify directory permissions
    - name: Verify directory permissions
      run: |
        ls -ld $dir

    # Copy files from BACKEND_FIAFIT to the cloned MAIN_PROYFIAFIT excluding .git and .github
    - name: Copy files to MAIN_PROYFIAFIT
      run: |
        rsync -av --exclude='.git' --exclude='.github' ./ $dir  # Copia archivos al directorio temporal

    # Commit and push changes to the 'BACK' branch in MAIN_PROYFIAFIT
    - name: Commit and push changes
      run: |
        cd $dir
        git add .
        git commit -m "Update from BACKEND_FIAFIT"
        git push origin BACK

    # Clean up the cloned repository
    - name: Clean up
      run: rm -rf $dir
