name: Push to MAIN_FIAFIT

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (BACK_FIAFIT)
    - name: Checkout BACK_FIAFIT
      uses: actions/checkout@v2

    # Configure Git with credentials
    - name: Set up Git
      run: |
        git config --global user.name 'gonzalo1998peru'
        git config --global user.email 'gonzalo_huertas_oliva@outlook.es'

    # Clone the target repository MAIN_FIAFIT
     name: Create unique target directory and clone MAIN_PROYFIAFIT
     env:
        TOKEN_BACK: ${{ secrets.access_token_gonzalo }}  # Secreto configurado con el valor de 'token1'
      run: |
        dir=$(mktemp -d)
        git clone --branch main https://x-access-token:${{ secrets.access_token_gonzalo }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git $dir


    # Copy files from BACK_FIAFIT to MAIN_FIAFIT
    - name: Copy files to MAIN_FIAFIT
      run: |
        cp -r ./* ../MAIN_FIAFIT/

    # Commit and push changes to MAIN_FIAFIT
    - name: Commit and push changes
      run: |
        cd MAIN_FIAFIT
        git add .
        git commit -m "Update from BACK_FIAFIT"
        git push origin back

    # Clean up the cloned repository
    - name: Clean up
      run: rm -rf MAIN_FIAFIT/
