name: Push to MAIN_FIAFIT

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (BACKEND_FIAFIT)
    - name: Checkout BACKEND_FIAFIT
      uses: actions/checkout@v2

    # Configurar Git con las credenciales
    - name: Set up Git
      run: |
        git config --global user.name 'gonzalo1998peru'
        git config --global user.email 'gonzalo_huertas_oliva@outlook.es'

    # Clone the MAIN_FIAFIT repository (branch 'BACK') into TEMPORAL_CHANGE directory
    - name: Clone MAIN_PROYFIAFIT
      run: |
        git clone --branch main https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git TEMPORAL_CHANGE

    # Copy files from BACKEND_FIAFIT to MAIN_PROYFIAFIT
    - name: Copy files from BACKEND_FIAFIT to MAIN_PROYFIAFIT
      run: |
        cp -R ./* TEMPORAL_CHANGE/
        cd TEMPORAL_CHANGE
        git add .
        
    # Check for changes before committing
    - name: Commit and push changes
      run: |
        cd TEMPORAL_CHANGE
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Sync from BACKEND_FIAFIT"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git main
        fi
