name: Push changes to MAIN_PROYFIAFIT

on:
  push:
    branches:
      - main  # Este flujo se activa cuando hay un push en la rama 'main' de BACKEND_FIAFIT

jobs:
  push_to_back:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código de la rama 'main' de BACKEND_FIAFIT
    - name: Checkout BACKEND_FIAFIT main branch
      uses: actions/checkout@v2
      with:
        ref: main

    # Paso 2: Configurar Git para los commits automáticos
    - name: Set up Git
      run: |
        git config --global user.name "gonzalo1998peru"
        git config --global user.email "gonzalo_huertas_oliva@outlook.es"

    # Paso 3: Crear un directorio temporal único para clonar el repositorio MAIN_PROYFIAFIT en la rama BACK
    - name: Create unique target directory and clone MAIN_PROYFIAFIT (BACK branch)
      env:
        TOKEN_BACK: ${{ secrets.access_token_gonzalo }}  # Secreto configurado con el valor de 'token1'
      run: |
        dir=$(mktemp -d)
        # Hacemos un fetch para asegurarnos de que tenemos la rama BACK disponible
        git clone https://x-access-token:${{ secrets.access_token_gonzalo }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git $dir
        cd $dir
        git fetch origin BACK  # Traemos todas las ramas, incluyendo BACK
        git checkout BACK      # Cambiamos a la rama BACK

    # Paso 4: Sincronizar los cambios de BACKEND_FIAFIT main a MAIN_PROYFIAFIT BACK
    - name: Sync changes to MAIN_PROYFIAFIT BACK branch
      run: |
        rsync -av --exclude='.git' ./ $dir/
        cd $dir
        git add .
        git commit -m "Auto-sync from BACKEND_FIAFIT/main"
        git push origin BACK  # Asegurarse de hacer push a la rama BACK
